### ISSUE TITLE
Present the csv file name

### ISSUE THREAD

**Issue by Chunting** [PlotJuggler/PlotJuggler#77]
Hi, could you please add a new feature that provides the csv file name in the titlebar?
Since sometimes I plot the different csv files whose labels are identical, it's not inconvenient to tell them.
![image](https://user-images.githubusercontent.com/3312409/37128730-6f5c5a0c-2249-11e8-84c1-2e6e257957fe.png)

Thanks.
Chunting
[2018_03_07_18_11_29.zip](https://github.com/facontidavide/PlotJuggler/files/1791559/2018_03_07_18_11_29.zip)

**Comment by facontidavide** [comment]
Hi,

by "titlebar" you mean the Window Title that in your screenshot is "PlotJuggler", I guess.
That would make sense for application like Office, where each window has a single open document at a time.

But in PlotJuggler you are able to load BOTH the file at the same time; since you can open multiple files simultaneously.

Unfortunately, in your particular case, as you said you can't, because of the labels.
Another DataImport Plugin use an optional "name prefix" to solve this issue, but the CSV loader doesn't have this feature.

I guess it make sense to add it...

**Comment by Chunting** [comment]
Thanks.
Your suggestion makes sense. I'm going to add prefix to the label.
Chunting

**Comment by Chunting** [comment]
Hi, sorry to disturb you again.
Now I rewrote my csv but met with another problem.
In my case, if some cells in first row are empty, then I can't plot those columns, such as the
FT_X | FT_Y | FT_Z | FT_A | FT_B | FT_C
Would you mind fixing it?

[FTKUKA_TimeEvent2.csv.zip](https://github.com/facontidavide/PlotJuggler/files/1868455/FTKUKA_TimeEvent2.csv.zip)

Thanks,
Chunting

**Comment by kobytg17** [comment]
Hi @facontidavide,

I was about to request the same feature that @Chunting described above.
I understand the problem with the multiple file usecase.

Can I suggest some compromise? I suggest the following:
When only one file is open - add its name to the titlebar. Otherwise, add "multiple datasources"

WDYT?
